import { Muscle } from './types';

export const ANATOMY_DATA: Muscle[] = [
  // REGIÃO GLÚTEA SUPERFICIAL
  {
    id: 'g-max',
    region: 'Região Glútea',
    compartment: 'Superficial',
    name: 'Glúteo Máximo',
    origin: 'Linha glútea post., sacro, cóccix',
    insertion: 'Trato iliotibial e tuberosidade glútea',
    innervation: 'N. Glúteo Inferior',
    vascularization: 'A. Glútea Sup. e Inf.',
    veins: 'V. Glútea Sup. e Inf.',
    action: 'Extensão e rot. lateral da coxa.',
  },
  {
    id: 'g-med',
    region: 'Região Glútea',
    compartment: 'Superficial',
    name: 'Glúteo Médio',
    origin: 'Face externa do ílio',
    insertion: 'Trocânter maior (lateral)',
    innervation: 'N. Glúteo Superior',
    vascularization: 'A. Glútea Superior',
    veins: 'V. Glútea Superior',
    action: 'Abdução e rot. medial da coxa.',
  },
  {
    id: 'g-min',
    region: 'Região Glútea',
    compartment: 'Superficial',
    name: 'Glúteo Mínimo',
    origin: 'Face externa do ílio',
    insertion: 'Trocânter maior (anterior)',
    innervation: 'N. Glúteo Superior',
    vascularization: 'A. Glútea Superior',
    veins: 'V. Glútea Superior',
    action: 'Abdução e rot. medial da coxa.',
  },
  {
    id: 'tfl',
    region: 'Região Glútea',
    compartment: 'Superficial',
    name: 'Tensor da Fáscia Lata',
    origin: 'Crista ilíaca e EIAS',
    insertion: 'Trato iliotibial',
    innervation: 'N. Glúteo Superior',
    vascularization: 'A. Circunflexa Femoral Lat.',
    veins: 'V. Circunflexa Femoral Lat.',
    action: 'Flexão, abdução e rot. medial.',
  },

  // REGIÃO GLÚTEA PROFUNDA
  {
    id: 'piriforme',
    region: 'Região Glútea',
    compartment: 'Profunda (Pelvi-trocantéricos)',
    name: 'Piriforme',
    origin: 'Sacro (face anterior)',
    insertion: 'Trocânter maior',
    innervation: 'N. para o m. Piriforme',
    vascularization: 'A. Glútea Sup. e Inf.',
    veins: 'V. Glútea Sup. e Inf.',
    action: 'Rot. lateral e abdução.',
  },
  {
    id: 'obt-int',
    region: 'Região Glútea',
    compartment: 'Profunda (Pelvi-trocantéricos)',
    name: 'Obturador Interno',
    origin: 'Membrana obturatória (int)',
    insertion: 'Trocânter maior',
    innervation: 'N. para o Obt. Interno',
    vascularization: 'A. Obturatória',
    veins: 'V. Obturatória',
    action: 'Rot. lateral da coxa.',
  },
  {
    id: 'gem-sup',
    region: 'Região Glútea',
    compartment: 'Profunda (Pelvi-trocantéricos)',
    name: 'Gêmeo Superior',
    origin: 'Espinha isquiática',
    insertion: 'Tendão do Obt. Interno',
    innervation: 'N. para o Obt. Interno',
    vascularization: 'A. Glútea Inferior',
    veins: 'V. Glútea Inferior',
    action: 'Rot. lateral da coxa.',
  },
  {
    id: 'gem-inf',
    region: 'Região Glútea',
    compartment: 'Profunda (Pelvi-trocantéricos)',
    name: 'Gêmeo Inferior',
    origin: 'Tuberosidade isquiática',
    insertion: 'Tendão do Obt. Interno',
    innervation: 'N. para o Quad. Femoral',
    vascularization: 'A. Glútea Inferior',
    veins: 'V. Glútea Inferior',
    action: 'Rot. lateral da coxa.',
  },
  {
    id: 'quad-fem',
    region: 'Região Glútea',
    compartment: 'Profunda (Pelvi-trocantéricos)',
    name: 'Quadrado Femoral',
    origin: 'Tuberosidade isquiática',
    insertion: 'Crista intertrocantérica',
    innervation: 'N. para o Quad. Femoral',
    vascularization: 'A. Glútea Inferior',
    veins: 'V. Glútea Inferior',
    action: 'Rot. lateral da coxa.',
  },
  {
    id: 'obt-ext',
    region: 'Região Glútea',
    compartment: 'Profunda (Pelvi-trocantéricos)',
    name: 'Obturador Externo',
    origin: 'Margens do forame obturado e membrana obturatória',
    insertion: 'Fossa trocantérica do fêmur',
    innervation: 'N. Obturador (L2-L4)',
    vascularization: 'Artéria obturatória e artéria circunflexa femoral medial',
    veins: 'Veia obturatória e veia circunflexa femoral medial',
    action: 'Rotação lateral do quadril',
  },

  // COXA ANTERIOR
  {
    id: 'sartorio',
    region: 'Coxa',
    compartment: 'Anterior',
    name: 'Sartório',
    origin: 'EIAS',
    insertion: 'Tíbia (Pata de ganso)',
    innervation: 'N. Femoral',
    vascularization: 'A. Femoral',
    veins: 'V. Femoral',
    action: 'Flexão, abd., rot. lat. coxa; flexão joelho.',
  },
  {
    id: 'reto-fem',
    region: 'Coxa',
    compartment: 'Anterior',
    name: 'Reto Femoral',
    origin: 'EIAI e ílio',
    insertion: 'Tuberosidade da tíbia',
    innervation: 'N. Femoral',
    vascularization: 'A. Circunflexa Femoral Lat.',
    veins: 'V. Circunflexa Femoral Lat.',
    action: 'Flexão coxa e extensão joelho.',
  },
  {
    id: 'vasto-lat',
    region: 'Coxa',
    compartment: 'Anterior',
    name: 'Vasto Lateral',
    origin: 'Trocânter maior, linha áspera',
    insertion: 'Tuberosidade da tíbia',
    innervation: 'N. Femoral',
    vascularization: 'A. Circunflexa Femoral Lat.',
    veins: 'V. Circunflexa Femoral Lat.',
    action: 'Extensão do joelho.',
  },
  {
    id: 'vasto-med',
    region: 'Coxa',
    compartment: 'Anterior',
    name: 'Vasto Medial',
    origin: 'Linha intertrocantérica',
    insertion: 'Tuberosidade da tíbia',
    innervation: 'N. Femoral',
    vascularization: 'A. Femoral',
    veins: 'V. Femoral',
    action: 'Extensão do joelho.',
  },
  {
    id: 'vasto-int',
    region: 'Coxa',
    compartment: 'Anterior',
    name: 'Vasto Intermédio',
    origin: 'Face anterior do fêmur',
    insertion: 'Tuberosidade da tíbia',
    innervation: 'N. Femoral',
    vascularization: 'A. Femoral Profunda',
    veins: 'V. Femoral Profunda',
    action: 'Extensão do joelho.',
  },
  {
    id: 'iliopsoas',
    region: 'Coxa',
    compartment: 'Anterior',
    name: 'Iliopsoas (Psoas maior + Ilíaco)',
    origin: 'Fossa ilíaca e v. lombares',
    insertion: 'Trocânter menor',
    innervation: 'N. Femoral / Ramos L1-L3',
    vascularization: 'A. Iliolombar e Femoral',
    veins: 'V. Iliolombar e Femoral',
    action: 'Flexão da coxa.',
  },

  // COXA POSTERIOR (Flexores do Joelho)
  {
    id: 'biceps-femoral',
    region: 'Coxa',
    compartment: 'Posterior (Isquiotibiais)',
    name: 'Bíceps Femoral',
    origin: 'Túber isquiático / Linha áspera',
    insertion: 'Cabeça da fíbula',
    innervation: 'N. Ciático',
    vascularization: 'A. Perfurantes (Profunda)',
    veins: 'V. Perfurantes (Profunda)',
    action: 'Flexão joelho e extensão coxa.',
  },
  {
    id: 'semitendineo',
    region: 'Coxa',
    compartment: 'Posterior (Isquiotibiais)',
    name: 'Semitendíneo',
    origin: 'Túber isquiático',
    insertion: 'Tíbia (Pata de ganso)',
    innervation: 'N. Ciático (Tibial)',
    vascularization: 'A. Perfurantes (Profunda)',
    veins: 'V. Perfurantes (Profunda)',
    action: 'Extensão coxa e flexão joelho.',
  },
  {
    id: 'semimembranaceo',
    region: 'Coxa',
    compartment: 'Posterior (Isquiotibiais)',
    name: 'Semimembranáceo',
    origin: 'Túber isquiático',
    insertion: 'Côndilo medial da tíbia',
    innervation: 'N. Ciático (Tibial)',
    vascularization: 'A. Perfurantes (Profunda)',
    veins: 'V. Perfurantes (Profunda)',
    action: 'Extensão coxa e flexão joelho.',
  },

  // COXA MEDIAL
  {
    id: 'pectineo',
    region: 'Coxa',
    compartment: 'Medial (Adutores)',
    name: 'Pectíneo',
    origin: 'Ramo superior do púbis',
    insertion: 'Linha pectínea (fêmur)',
    innervation: 'N. Femoral (e Obturatório)',
    vascularization: 'A. Circunflexa Femoral Med.',
    veins: 'V. Circunflexa Femoral Med.',
    action: 'Adução e flexão da coxa.',
  },
  {
    id: 'adutor-longo',
    region: 'Coxa',
    compartment: 'Medial (Adutores)',
    name: 'Adutor Longo',
    origin: 'Corpo do púbis',
    insertion: 'Linha áspera',
    innervation: 'N. Obturatório',
    vascularization: 'A. Femoral Profunda',
    veins: 'V. Femoral Profunda',
    action: 'Adução da coxa.',
  },
  {
    id: 'adutor-curto',
    region: 'Coxa',
    compartment: 'Medial (Adutores)',
    name: 'Adutor Curto',
    origin: 'Corpo e ramo inf. púbis',
    insertion: 'Linha áspera',
    innervation: 'N. Obturatório',
    vascularization: 'A. Femoral Profunda',
    veins: 'V. Femoral Profunda',
    action: 'Adução da coxa.',
  },
  {
    id: 'adutor-magno',
    region: 'Coxa',
    compartment: 'Medial (Adutores)',
    name: 'Adutor Magno',
    origin: 'Ramo isquiopúbico',
    insertion: 'Linha áspera e Tub. Adutor',
    innervation: 'N. Obturatório e Ciático',
    vascularization: 'A. Femoral Prof. e Obturatória',
    veins: 'V. Femoral Prof. e Obturatória',
    action: 'Adução potente e extensão.',
  },
  {
    id: 'gracil',
    region: 'Coxa',
    compartment: 'Medial (Adutores)',
    name: 'Grácil',
    origin: 'Corpo e ramo inf. púbis',
    insertion: 'Tíbia (Pata de ganso)',
    innervation: 'N. Obturatório',
    vascularization: 'A. Femoral Profunda',
    veins: 'V. Femoral Profunda',
    action: 'Adução coxa e flexão joelho.',
  },

  // PERNA ANTERIOR
  {
    id: 'tibial-ant',
    region: 'Perna',
    compartment: 'Anterior',
    name: 'Tibial Anterior',
    origin: 'Côndilo lat. tíbia',
    insertion: 'Cuneiforme med. / 1º meta',
    innervation: 'N. Fibular Profundo',
    vascularization: 'A. Tibial Anterior',
    veins: 'V. Tibial Anterior',
    action: 'Dorsiflexão e inversão.',
  },
  {
    id: 'ext-long-dedos',
    region: 'Perna',
    compartment: 'Anterior',
    name: 'Extensor Longo dos Dedos',
    origin: 'Côndilo lat. tíbia / fíbula',
    insertion: 'Falanges distais (2-5)',
    innervation: 'N. Fibular Profundo',
    vascularization: 'A. Tibial Anterior',
    veins: 'V. Tibial Anterior',
    action: 'Extensão dedos e dorsiflexão.',
  },
  {
    id: 'ext-long-halux',
    region: 'Perna',
    compartment: 'Anterior',
    name: 'Extensor Longo do Hálux',
    origin: 'Face anterior fíbula',
    insertion: 'Falange distal hálux',
    innervation: 'N. Fibular Profundo',
    vascularization: 'A. Tibial Anterior',
    veins: 'V. Tibial Anterior',
    action: 'Extensão hálux e dorsiflexão.',
  },
  {
    id: 'fibular-terc',
    region: 'Perna',
    compartment: 'Anterior',
    name: 'Fibular Terceiro',
    origin: 'Fíbula (distal)',
    insertion: 'Base do 5º metatarso',
    innervation: 'N. Fibular Profundo',
    vascularization: 'A. Tibial Anterior',
    veins: 'V. Tibial Anterior',
    action: 'Dorsiflexão e eversão.',
  },

  // PERNA LATERAL
  {
    id: 'fibular-longo',
    region: 'Perna',
    compartment: 'Lateral',
    name: 'Fibular Longo',
    origin: 'Cabeça/corpo fíbula',
    insertion: 'Cuneiforme med. / 1º meta',
    innervation: 'N. Fibular Superficial',
    vascularization: 'A. Fibular',
    veins: 'V. Fibular',
    action: 'Eversão e flexão plantar.',
  },
  {
    id: 'fibular-curto',
    region: 'Perna',
    compartment: 'Lateral',
    name: 'Fibular Curto',
    origin: 'Corpo fíbula (distal)',
    insertion: 'Base do 5º metatarso',
    innervation: 'N. Fibular Superficial',
    vascularization: 'A. Fibular',
    veins: 'V. Fibular',
    action: 'Eversão e flexão plantar.',
  },

  // PERNA POSTERIOR
  {
    id: 'gastrocnemio',
    region: 'Perna',
    compartment: 'Posterior',
    subCompartment: 'Superficial',
    name: 'Gastrocnêmio',
    origin: 'Côndilos do fêmur',
    insertion: 'Calcâneo',
    innervation: 'N. Tibial',
    vascularization: 'A. Sural e Poplítea',
    veins: 'V. Sural e Poplítea',
    action: 'Flexão plantar e flexão joelho.',
  },
  {
    id: 'soleo',
    region: 'Perna',
    compartment: 'Posterior',
    subCompartment: 'Superficial',
    name: 'Sóleo',
    origin: 'Tíbia e Fíbula (post)',
    insertion: 'Calcâneo',
    innervation: 'N. Tibial',
    vascularization: 'A. Poplítea e Tibial Post.',
    veins: 'V. Poplítea e Tibial Post.',
    action: 'Flexão plantar.',
  },
  {
    id: 'plantar',
    region: 'Perna',
    compartment: 'Posterior',
    subCompartment: 'Superficial',
    name: 'Plantar',
    origin: 'Linha supracondilar lat.',
    insertion: 'Calcâneo',
    innervation: 'N. Tibial',
    vascularization: 'A. Poplítea',
    veins: 'V. Poplítea',
    action: 'Auxilia flexão plantar.',
  },
  {
    id: 'popliteo',
    region: 'Perna',
    compartment: 'Posterior',
    subCompartment: 'Profundo',
    name: 'Poplíteo',
    origin: 'Côndilo lat. fêmur',
    insertion: 'Tíbia (posterior)',
    innervation: 'N. Tibial',
    vascularization: 'A. Poplítea',
    veins: 'V. Poplítea',
    action: 'Rot. medial tíbia (destrava joelho).',
  },
  {
    id: 'flex-long-halux',
    region: 'Perna',
    compartment: 'Posterior',
    subCompartment: 'Profundo',
    name: 'Flexor Longo do Hálux',
    origin: 'Fíbula (posterior)',
    insertion: 'Falange distal hálux',
    innervation: 'N. Tibial',
    vascularization: 'A. Fibular',
    veins: 'V. Fibular',
    action: 'Flexão hálux e flexão plantar.',
  },
  {
    id: 'flex-long-dedos',
    region: 'Perna',
    compartment: 'Posterior',
    subCompartment: 'Profundo',
    name: 'Flexor Longo dos Dedos',
    origin: 'Tíbia (posterior)',
    insertion: 'Falanges distais (2-5)',
    innervation: 'N. Tibial',
    vascularization: 'A. Tibial Posterior',
    veins: 'V. Tibial Posterior',
    action: 'Flexão dedos e flexão plantar.',
  },
  {
    id: 'tibial-post',
    region: 'Perna',
    compartment: 'Posterior',
    subCompartment: 'Profundo',
    name: 'Tibial Posterior',
    origin: 'Tíbia, fíbula e m. interóssea',
    insertion: 'Navicular/Cuneiformes',
    innervation: 'N. Tibial',
    vascularization: 'A. Fibular e Tibial Post.',
    veins: 'V. Fibular e Tibial Post.',
    action: 'Inversão e flexão plantar.',
  },

  // PÉ - 1ª CAMADA
  {
    id: 'flex-curto-dedos',
    region: 'Pé',
    compartment: 'Planta',
    subCompartment: '1ª Camada',
    name: 'Flexor Curto dos Dedos',
    origin: 'Calcâneo / Aponeurose',
    insertion: 'Falanges médias (2-5)',
    innervation: 'N. Plantar Medial',
    vascularization: 'A. Plantar Medial e Lat.',
    veins: 'V. Plantar Medial e Lat.',
    action: 'Flexão falanges médias.',
  },
  {
    id: 'abd-halux',
    region: 'Pé',
    compartment: 'Planta',
    subCompartment: '1ª Camada',
    name: 'Abdutor do Hálux',
    origin: 'Calcâneo',
    insertion: 'Falange prox. hálux',
    innervation: 'N. Plantar Medial',
    vascularization: 'A. Plantar Medial',
    veins: 'V. Plantar Medial',
    action: 'Abdução do hálux.',
  },
  {
    id: 'abd-minimo',
    region: 'Pé',
    compartment: 'Planta',
    subCompartment: '1ª Camada',
    name: 'Abdutor do Dedo Mínimo',
    origin: 'Calcâneo',
    insertion: 'Falange prox. 5º dedo',
    innervation: 'N. Plantar Lateral',
    vascularization: 'A. Plantar Lateral',
    veins: 'V. Plantar Lateral',
    action: 'Abdução do 5º dedo.',
  },

  // PÉ - 2ª CAMADA
  {
    id: 'quad-plantar',
    region: 'Pé',
    compartment: 'Planta',
    subCompartment: '2ª Camada',
    name: 'Quadrado Plantar',
    origin: 'Calcâneo',
    insertion: 'Tendão Flex. Longo Dedos',
    innervation: 'N. Plantar Lateral',
    vascularization: 'A. Plantar Lateral',
    veins: 'V. Plantar Lateral',
    action: 'Auxilia flexão (corrige vetor).',
  },
  {
    id: 'lumbrical-1',
    region: 'Pé',
    compartment: 'Planta',
    subCompartment: '2ª Camada',
    name: '1º Lumbrical',
    origin: 'Tendões Flex. Longo',
    insertion: 'Expansões extensoras',
    innervation: 'N. Plantar Medial',
    vascularization: 'A. Plantares (Arco)',
    veins: 'V. Plantares (Arco)',
    action: 'Flexão prox. / Extensão distal.',
  },
  {
    id: 'lumbricais-2-4',
    region: 'Pé',
    compartment: 'Planta',
    subCompartment: '2ª Camada',
    name: '2º, 3º e 4º Lumbricais',
    origin: 'Tendões Flex. Longo',
    insertion: 'Expansões extensoras',
    innervation: 'N. Plantar Lateral',
    vascularization: 'A. Plantares (Arco)',
    veins: 'V. Plantares (Arco)',
    action: 'Flexão prox. / Extensão distal.',
  },

  // PÉ - 3ª CAMADA
  {
    id: 'flex-curto-halux',
    region: 'Pé',
    compartment: 'Planta',
    subCompartment: '3ª Camada',
    name: 'Flexor Curto do Hálux',
    origin: 'Cuboide / Cuneiformes',
    insertion: 'Falange prox. hálux',
    innervation: 'N. Plantar Medial',
    vascularization: 'A. Plantar Medial',
    veins: 'V. Plantar Medial',
    action: 'Flexão do hálux.',
  },
  {
    id: 'adutor-halux',
    region: 'Pé',
    compartment: 'Planta',
    subCompartment: '3ª Camada',
    name: 'Adutor do Hálux',
    origin: 'Metatarsos 2-4 / Ligs.',
    insertion: 'Falange prox. hálux',
    innervation: 'N. Plantar Lateral',
    vascularization: 'A. Plantar Lateral',
    veins: 'V. Plantar Lateral',
    action: 'Adução do hálux.',
  },
  {
    id: 'flex-curto-minimo',
    region: 'Pé',
    compartment: 'Planta',
    subCompartment: '3ª Camada',
    name: 'Flexor Curto do Dedo Mínimo',
    origin: 'Base do 5º metatarso',
    insertion: 'Falange prox. 5º dedo',
    innervation: 'N. Plantar Lateral',
    vascularization: 'A. Plantar Lateral',
    veins: 'V. Plantar Lateral',
    action: 'Flexão do 5º dedo.',
  },
  
  // PÉ - 4ª CAMADA
  {
    id: 'inter-plantares',
    region: 'Pé',
    compartment: 'Planta',
    subCompartment: '4ª Camada',
    name: 'Interósseos Plantares (3 músculos)',
    origin: 'Metatarsos 3-5 (medial)',
    insertion: 'Falanges prox. 3-5',
    innervation: 'N. Plantar Lateral',
    vascularization: 'A. Plantar Lateral (Arco)',
    veins: 'V. Plantar Lateral (Arco)',
    action: 'Adução dos dedos.',
  },
  {
    id: 'inter-dorsais',
    region: 'Pé',
    compartment: 'Planta',
    subCompartment: '4ª Camada',
    name: 'Interósseos Dorsais (4 músculos)',
    origin: 'Metatarsos adjacentes',
    insertion: 'Falanges prox. 2-4',
    innervation: 'N. Plantar Lateral',
    vascularization: 'A. Plantar Lateral (Arco)',
    veins: 'V. Plantar Lateral (Arco)',
    action: 'Abdução dos dedos.',
  },

  // PÉ - DORSO
  {
    id: 'ext-curto-dedos',
    region: 'Pé',
    compartment: 'Dorso',
    name: 'Extensor Curto dos Dedos',
    origin: 'Calcâneo',
    insertion: 'Tendões do Ext. Longo',
    innervation: 'N. Fibular Profundo',
    vascularization: 'A. Dorsal do Pé',
    veins: 'V. Dorsal do Pé',
    action: 'Extensão dedos (2-4).',
  },
  {
    id: 'ext-curto-halux',
    region: 'Pé',
    compartment: 'Dorso',
    name: 'Extensor Curto do Hálux',
    origin: 'Calcâneo',
    insertion: 'Falange prox. hálux',
    innervation: 'N. Fibular Profundo',
    vascularization: 'A. Dorsal do Pé',
    veins: 'V. Dorsal do Pé',
    action: 'Extensão do hálux.',
  },
];