import { Muscle } from './types';

export const ANATOMY_DATA: Muscle[] = [
  // REGIÃO GLÚTEA SUPERFICIAL
  {
    id: 'g-max',
    region: 'Região Glútea',
    compartment: 'Superficial',
    name: 'Glúteo Máximo',
    origin: 'Face posterior do ílio, dorso do sacro e cóccix, ligamento sacrotuberoso',
    insertion: 'Trato iliotibial e tuberosidade glútea do fêmur',
    innervation: 'N. Glúteo Inferior (L5-S2)',
    vascularization: 'Artérias glúteas superior e inferior',
    veins: 'Veias glúteas superior e inferior',
    action: 'Extensão potente da coxa, rotação lateral, estabilização do joelho e da pelve',
  },
  {
    id: 'g-med',
    region: 'Região Glútea',
    compartment: 'Superficial',
    name: 'Glúteo Médio',
    origin: 'Face lateral do ílio entre as linhas glúteas anterior e posterior',
    insertion: 'Face lateral do trocânter maior',
    innervation: 'N. Glúteo Superior (L4-S1)',
    vascularization: 'Artéria glútea superior',
    veins: 'Veia glútea superior',
    action: 'Abdução e rotação medial da coxa; mantém a pelve nivelada',
  },
  {
    id: 'g-min',
    region: 'Região Glútea',
    compartment: 'Superficial',
    name: 'Glúteo Mínimo',
    origin: 'Face lateral do ílio entre as linhas glúteas anterior e inferior',
    insertion: 'Face anterior do trocânter maior',
    innervation: 'N. Glúteo Superior (L4-S1)',
    vascularization: 'Artéria glútea superior',
    veins: 'Veia glútea superior',
    action: 'Abdução, rotação medial e estabilização da pelve',
  },
  {
    id: 'tfl',
    region: 'Região Glútea',
    compartment: 'Superficial',
    name: 'Tensor da Fáscia Lata',
    origin: 'Crista ilíaca (porção anterior) e EIAS (Espinha Ilíaca Anterosuperior)',
    insertion: 'Trato iliotibial (até o côndilo lateral da tíbia)',
    innervation: 'N. Glúteo Superior (L4-S1)',
    vascularization: 'Artéria glútea superior e artéria circunflexa femoral lateral',
    veins: 'Veia glútea superior',
    action: 'Flexão, abdução e rotação medial da coxa; estabiliza o joelho em extensão',
  },

  // REGIÃO GLÚTEA PROFUNDA
  {
    id: 'piriforme',
    region: 'Região Glútea',
    compartment: 'Profunda (Pelvi-trocantéricos)',
    name: 'Piriforme',
    origin: 'Face anterior do sacro (S2-S4) e ligamento sacrotuberoso',
    insertion: 'Borda superior do trocânter maior',
    innervation: 'Ramos Ventrais de L5-S2',
    vascularization: 'Artérias glúteas superior e inferior, artéria pudenda interna',
    veins: 'Veias glúteas superior e inferior',
    action: 'Rotação lateral da coxa estendida, abdução da coxa fletida',
  },
  {
    id: 'obt-int',
    region: 'Região Glútea',
    compartment: 'Profunda (Pelvi-trocantéricos)',
    name: 'Obturador Interno',
    origin: 'Face pélvica da membrana obturatória e ossos adjacentes',
    insertion: 'Face medial do trocânter maior',
    innervation: 'N. do Obturador Interno (L5-S1)',
    vascularization: 'Artéria obturatória e artéria pudenda interna',
    veins: 'Veia obturatória e veia pudenda interna',
    action: 'Rotação lateral, abdução da coxa fletida, estabiliza a cabeça femoral',
  },
  {
    id: 'gem-sup',
    region: 'Região Glútea',
    compartment: 'Profunda (Pelvi-trocantéricos)',
    name: 'Gêmeo Superior',
    origin: 'Espinha isquiática',
    insertion: 'Face medial do trocânter maior',
    innervation: 'N. do Obturador Interno (L5-S1)',
    vascularization: 'Artéria glútea inferior e artéria pudenda interna',
    veins: 'Veia glútea inferior',
    action: 'Rotação lateral, abdução da coxa fletida',
  },
  {
    id: 'gem-inf',
    region: 'Região Glútea',
    compartment: 'Profunda (Pelvi-trocantéricos)',
    name: 'Gêmeo Inferior',
    origin: 'Tuberiosidade isquiática',
    insertion: 'Face medial do trocânter maior',
    innervation: 'N. do Quadrado Femoral (L5-S1)',
    vascularization: 'Artéria circunflexa femoral medial',
    veins: 'Veia circunflexa femoral medial',
    action: 'Rotação lateral da coxa, estabilização',
  },
  {
    id: 'quad-fem',
    region: 'Região Glútea',
    compartment: 'Profunda (Pelvi-trocantéricos)',
    name: 'Quadrado Femoral',
    origin: 'Borda lateral da tuberosidade isquiática',
    insertion: 'Tubérculo quadrado da crista intertrocantérica',
    innervation: 'N. do Quadrado Femoral (L5-S1)',
    vascularization: 'Artéria circunflexa femoral medial',
    veins: 'Veia circunflexa femoral medial',
    action: 'Rotador lateral forte, estabiliza a cabeça do fêmur',
  },
  {
    id: 'obt-ext',
    region: 'Região Glútea',
    compartment: 'Profunda (Pelvi-trocantéricos)',
    name: 'Obturador Externo',
    origin: 'Margens do forame obturado e membrana obturatória',
    insertion: 'Fossa trocantérica do fêmur',
    innervation: 'N. Obturador (L2-L4)',
    vascularization: 'Artéria obturatória e artéria circunflexa femoral medial',
    veins: 'Veia obturatória e veia circunflexa femoral medial',
    action: 'Rotação lateral do quadril',
  },

  // COXA ANTERIOR
  {
    id: 'sartorio',
    region: 'Coxa',
    compartment: 'Anterior',
    name: 'Sartório',
    origin: 'EIAS (Espinha Ilíaca Anterosuperior)',
    insertion: 'Face medial da tíbia (Pata de Ganso)',
    innervation: 'N. Femoral (L2-L3)',
    vascularization: 'Artéria femoral',
    veins: 'Veia femoral e veia safena magna',
    action: 'Flexão, abdução e rotação lateral do quadril; flexão do joelho',
  },
  {
    id: 'reto-fem',
    region: 'Coxa',
    compartment: 'Anterior',
    name: 'Reto Femoral',
    origin: 'EIAI (Espinha Ilíaca Anteroinferior) e sulco supra-acetabular',
    insertion: 'Base da patela / Lig. patelar na tuberosidade da tíbia',
    innervation: 'N. Femoral (L2-L4)',
    vascularization: 'Artéria circunflexa femoral lateral e artéria femoral',
    veins: 'Veia femoral e veia femoral profunda',
    action: 'Extensão do joelho, auxilia flexão do quadril',
  },
  {
    id: 'vasto-lat',
    region: 'Coxa',
    compartment: 'Anterior',
    name: 'Vasto Lateral',
    origin: 'Trocânter maior e lábio lateral da linha áspera',
    insertion: 'Patela / Lig. patelar na tuberosidade da tíbia',
    innervation: 'N. Femoral (L2-L4)',
    vascularization: 'Artéria circunflexa femoral lateral e artéria femoral profunda',
    veins: 'Veia circunflexa femoral lateral e veia femoral profunda',
    action: 'Extensão do joelho',
  },
  {
    id: 'vasto-med',
    region: 'Coxa',
    compartment: 'Anterior',
    name: 'Vasto Medial',
    origin: 'Linha intertrocantérica e lábio medial da linha áspera',
    insertion: 'Patela / Lig. patelar na tuberosidade da tíbia',
    innervation: 'N. Femoral (L2-L4)',
    vascularization: 'Artéria femoral e artéria femoral profunda',
    veins: 'Veia femoral e veia femoral profunda',
    action: 'Extensão do joelho',
  },
  {
    id: 'vasto-int',
    region: 'Coxa',
    compartment: 'Anterior',
    name: 'Vasto Intermédio',
    origin: 'Face anterior e lateral do fêmur',
    insertion: 'Patela / Lig. patelar na tuberosidade da tíbia',
    innervation: 'N. Femoral (L2-L4)',
    vascularization: 'Artéria circunflexa femoral lateral e artéria femoral profunda',
    veins: 'Veia femoral profunda',
    action: 'Extensão do joelho',
  },
  {
    id: 'iliopsoas',
    region: 'Coxa',
    compartment: 'Anterior',
    name: 'Iliopsoas (Psoas maior + Ilíaco)',
    origin: 'Psoas maior: Processos transversos L1-L5 / Ilíaco: Fossa ilíaca',
    insertion: 'Trocânter menor do fêmur',
    innervation: 'Ramos Ventrais (L1-L3) [Psoas] + N. Femoral (L2-L3) [Ilíaco]',
    vascularization: 'Artérias lombares, iliolombar, circunflexa ilíaca profunda e femoral',
    veins: 'Veias lombares e veia ilíaca comum',
    action: 'Principal flexor do quadril',
  },

  // COXA POSTERIOR (Flexores do Joelho)
  {
    id: 'biceps-femoral',
    region: 'Coxa',
    compartment: 'Posterior (Isquiotibiais)',
    name: 'Bíceps Femoral',
    origin: 'Cabeça Longa: Túber isquiático / Cabeça Curta: Linha áspera (lábio lateral) e linha supracondilar lateral',
    insertion: 'Cabeça da fíbula',
    innervation: 'Cabeça Longa: N. Tibial (L5-S2) + Cabeça Curta: N. Fibular Comum (L5-S2)',
    vascularization: 'Artérias perfurantes da femoral profunda e artéria poplítea',
    veins: 'Veia profunda da coxa, veia poplítea e veias perfurantes',
    action: 'Extensão do quadril (cabeça longa), flexão e rotação lateral do joelho',
  },
  {
    id: 'semitendineo',
    region: 'Coxa',
    compartment: 'Posterior (Isquiotibiais)',
    name: 'Semitendíneo',
    origin: 'Túber isquiático',
    insertion: 'Face medial da tíbia (Pata de Ganso)',
    innervation: 'N. Tibial (L5-S2)',
    vascularization: 'Artérias perfurantes da femoral profunda',
    veins: 'Veias perfurantes e veia profunda da coxa',
    action: 'Extensão do quadril, flexão e rotação medial do joelho',
  },
  {
    id: 'semimembranaceo',
    region: 'Coxa',
    compartment: 'Posterior (Isquiotibiais)',
    name: 'Semimembranáceo',
    origin: 'Túber isquiático',
    insertion: 'Côndilo medial da tíbia (posterior)',
    innervation: 'N. Tibial (L5-S2)',
    vascularization: 'Artérias perfurantes da femoral profunda e artéria poplítea',
    veins: 'Veias perfurantes e veia poplítea',
    action: 'Extensão do quadril, flexão e rotação medial do joelho',
  },

  // COXA MEDIAL
  {
    id: 'pectineo',
    region: 'Coxa',
    compartment: 'Medial (Adutores)',
    name: 'Pectíneo',
    origin: 'Linha pectínea do púbis',
    insertion: 'Linha pectínea do fêmur',
    innervation: 'N. Femoral (L2-L3)',
    vascularization: 'Artéria circunflexa femoral medial e artéria obturatória',
    veins: 'Veia femoral e veia obturatória',
    action: 'Adução e flexão do quadril',
  },
  {
    id: 'adutor-longo',
    region: 'Coxa',
    compartment: 'Medial (Adutores)',
    name: 'Adutor Longo',
    origin: 'Corpo do púbis',
    insertion: 'Linha áspera (terço médio)',
    innervation: 'N. Obturador (L2-L4)',
    vascularization: 'Artéria femoral profunda e artéria obturatória',
    veins: 'Veia femoral profunda e veia obturatória',
    action: 'Adução do quadril',
  },
  {
    id: 'adutor-curto',
    region: 'Coxa',
    compartment: 'Medial (Adutores)',
    name: 'Adutor Curto',
    origin: 'Corpo e ramo inferior do púbis',
    insertion: 'Linha pectínea e parte proximal da linha áspera',
    innervation: 'N. Obturador (L2-L4)',
    vascularization: 'Artéria femoral profunda e artéria obturatória',
    veins: 'Veia femoral profunda e veia obturatória',
    action: 'Adução e flexão do quadril',
  },
  {
    id: 'adutor-magno',
    region: 'Coxa',
    compartment: 'Medial (Adutores)',
    name: 'Adutor Magno',
    origin: 'Porção Adutora: Ramo inferior do púbis e ramo do ísquio / Porção Isquiática: Túber isquiático',
    insertion: 'Tuberosidade glútea, linha áspera, linha supracondilar medial e tubérculo do adutor',
    innervation: 'Porção Adutora: N. Obturador (L2-L4) + Porção Isquiática: N. Tibial (L4-S3)',
    vascularization: 'Artéria femoral profunda, artéria obturatória e artéria poplítea',
    veins: 'Veia femoral profunda e veia poplítea',
    action: 'Adução e flexão do quadril (porção adutora); Extensão do quadril (porção isquiática)',
  },
  {
    id: 'gracil',
    region: 'Coxa',
    compartment: 'Medial (Adutores)',
    name: 'Grácil',
    origin: 'Corpo e ramo inferior do púbis',
    insertion: 'Parte superior da face medial da tíbia (Pata de Ganso)',
    innervation: 'N. Obturador (L2-L4)',
    vascularization: 'Artéria femoral profunda e artéria circunflexa femoral medial',
    veins: 'Veia femoral profunda',
    action: 'Adução do quadril, flexão e rotação medial do joelho',
  },

  // PERNA ANTERIOR
  {
    id: 'tibial-ant',
    region: 'Perna',
    compartment: 'Anterior',
    name: 'Tibial Anterior',
    origin: 'Côndilo lateral e face lateral da tíbia',
    insertion: 'Cuneiforme medial e base do 1º metatarso',
    innervation: 'N. Fibular Profundo (L4-S1)',
    vascularization: 'Artéria tibial anterior',
    veins: 'Veias tibiais anteriores',
    action: 'Dorsiflexão e inversão do pé',
  },
  {
    id: 'ext-long-dedos',
    region: 'Perna',
    compartment: 'Anterior',
    name: 'Extensor Longo dos Dedos',
    origin: 'Côndilo lateral da tíbia e fíbula anterior',
    insertion: 'Falanges médias e distais dos dedos 2-5',
    innervation: 'N. Fibular Profundo (L4-S1)',
    vascularization: 'Artéria tibial anterior',
    veins: 'Veias tibiais anteriores',
    action: 'Extensão dos dedos e dorsiflexão',
  },
  {
    id: 'ext-long-halux',
    region: 'Perna',
    compartment: 'Anterior',
    name: 'Extensor Longo do Hálux',
    origin: 'Face anterior da fíbula',
    insertion: 'Falange distal do hálux',
    innervation: 'N. Fibular Profundo (L4-S1)',
    vascularization: 'Artéria tibial anterior',
    veins: 'Veias tibiais anteriores',
    action: 'Extensão do hálux e dorsiflexão',
  },
  {
    id: 'fibular-terc',
    region: 'Perna',
    compartment: 'Anterior',
    name: 'Fibular Terceiro',
    origin: 'Terço distal da fíbula anterior',
    insertion: 'Base do 5º metatarso',
    innervation: 'N. Fibular Profundo (L4-S1)',
    vascularization: 'Artéria tibial anterior',
    veins: 'Veias tibiais anteriores',
    action: 'Dorsiflexão e eversão',
  },

  // PERNA LATERAL
  {
    id: 'fibular-longo',
    region: 'Perna',
    compartment: 'Lateral',
    name: 'Fibular Longo',
    origin: 'Cabeça e face lateral superior da fíbula',
    insertion: 'Base do 1º metatarso e cuneiforme medial (plantar)',
    innervation: 'N. Fibular Superficial (L5-S1)',
    vascularization: 'Artéria fibular e artéria tibial anterior',
    veins: 'Veias fibulares',
    action: 'Eversão e flexão plantar',
  },
  {
    id: 'fibular-curto',
    region: 'Perna',
    compartment: 'Lateral',
    name: 'Fibular Curto',
    origin: 'Face lateral inferior da fíbula',
    insertion: 'Base do 5º metatarso',
    innervation: 'N. Fibular Superficial (L5-S1)',
    vascularization: 'Artéria fibular e artéria tibial anterior',
    veins: 'Veias fibulares',
    action: 'Eversão do pé',
  },

  // PERNA POSTERIOR
  {
    id: 'gastrocnemio',
    region: 'Perna',
    compartment: 'Posterior',
    subCompartment: 'Superficial',
    name: 'Gastrocnêmio',
    origin: 'Côndilos lateral e medial do fêmur',
    insertion: 'Calcâneo (via tendão do calcâneo/Aquiles)',
    innervation: 'N. Tibial (S1-S2)',
    vascularization: 'Artérias surais (ramos da artéria poplítea)',
    veins: 'Veias poplíteas e veia safena parva',
    action: 'Flexão plantar do pé e flexão do joelho',
  },
  {
    id: 'soleo',
    region: 'Perna',
    compartment: 'Posterior',
    subCompartment: 'Superficial',
    name: 'Sóleo',
    origin: 'Cabeça da fíbula e linha solear da tíbia',
    insertion: 'Calcâneo (via tendão do calcâneo/Aquiles)',
    innervation: 'N. Tibial (S1-S2)',
    vascularization: 'Artéria poplítea, artéria tibial posterior e artéria fibular',
    veins: 'Veias poplíteas e veias tibiais posteriores',
    action: 'Flexão plantar do pé',
  },
  {
    id: 'plantar',
    region: 'Perna',
    compartment: 'Posterior',
    subCompartment: 'Superficial',
    name: 'Plantar',
    origin: 'Linha supracondilar lateral do fêmur',
    insertion: 'Calcâneo',
    innervation: 'N. Tibial (S1-S2)',
    vascularization: 'Artéria poplítea',
    veins: 'Veia poplítea',
    action: 'Flexão do joelho e flexão plantar (fraca)',
  },
  {
    id: 'popliteo',
    region: 'Perna',
    compartment: 'Posterior',
    subCompartment: 'Profundo',
    name: 'Poplíteo',
    origin: 'Côndilo lateral do fêmur',
    insertion: 'Face posterior da tíbia (acima da linha solear)',
    innervation: 'N. Tibial (L4-S1)',
    vascularization: 'Artéria poplítea',
    veins: 'Veia poplítea',
    action: 'Flexão fraca do joelho e rotação medial da tíbia (desbloqueia o joelho)',
  },
  {
    id: 'flex-long-halux',
    region: 'Perna',
    compartment: 'Posterior',
    subCompartment: 'Profundo',
    name: 'Flexor Longo do Hálux',
    origin: 'Face posterior da fíbula (2/3 inferiores)',
    insertion: 'Base da falange distal do hálux',
    innervation: 'N. Tibial (S2-S3)',
    vascularization: 'Artéria fibular',
    veins: 'Veias fibulares',
    action: 'Flexão do hálux e suporte do arco longitudinal',
  },
  {
    id: 'flex-long-dedos',
    region: 'Perna',
    compartment: 'Posterior',
    subCompartment: 'Profundo',
    name: 'Flexor Longo dos Dedos',
    origin: 'Face posterior da tíbia',
    insertion: 'Bases das falanges distais dos dedos 2-5',
    innervation: 'N. Tibial (S2-S3)',
    vascularization: 'Artéria tibial posterior',
    veins: 'Veias tibiais posteriores',
    action: 'Flexão dos dedos 2-5 e flexão plantar',
  },
  {
    id: 'tibial-post',
    region: 'Perna',
    compartment: 'Posterior',
    subCompartment: 'Profundo',
    name: 'Tibial Posterior',
    origin: 'Membrana interóssea, tíbia e fíbula posteriores',
    insertion: 'Navicular, cuneiformes, cuboide e bases dos metatarsos 2-4',
    innervation: 'N. Tibial (L4-L5)',
    vascularization: 'Artéria fibular e artéria tibial posterior',
    veins: 'Veias tibiais posteriores e veias fibulares',
    action: 'Flexão plantar e inversão do pé',
  },

  // PÉ - 1ª CAMADA
  {
    id: 'flex-curto-dedos',
    region: 'Pé',
    compartment: 'Planta',
    subCompartment: '1ª Camada',
    name: 'Flexor Curto dos Dedos',
    origin: 'Processo medial da tuberosidade do calcâneo',
    insertion: 'Lados das falanges médias dos dedos 2-5',
    innervation: 'N. Plantar Medial (S2-S3)',
    vascularization: 'Artérias plantares medial e lateral',
    veins: 'Veias plantares medial e lateral',
    action: 'Flexão das falanges médias dos dedos 2-5',
  },
  {
    id: 'abd-halux',
    region: 'Pé',
    compartment: 'Planta',
    subCompartment: '1ª Camada',
    name: 'Abdutor do Hálux',
    origin: 'Processo medial da tuberosidade do calcâneo',
    insertion: 'Base da falange proximal do hálux (medial)',
    innervation: 'N. Plantar Medial (S2-S3)',
    vascularization: 'Artéria plantar medial',
    veins: 'Veia plantar medial',
    action: 'Abdução e flexão do hálux',
  },
  {
    id: 'abd-minimo',
    region: 'Pé',
    compartment: 'Planta',
    subCompartment: '1ª Camada',
    name: 'Abdutor do Dedo Mínimo',
    origin: 'Processos lateral e medial da tuberosidade do calcâneo',
    insertion: 'Base da falange proximal do 5º dedo',
    innervation: 'N. Plantar Lateral (S2-S3)',
    vascularization: 'Artéria plantar lateral',
    veins: 'Veia plantar lateral',
    action: 'Abdução e flexão do dedo mínimo',
  },

  // PÉ - 2ª CAMADA
  {
    id: 'quad-plantar',
    region: 'Pé',
    compartment: 'Planta',
    subCompartment: '2ª Camada',
    name: 'Quadrado Plantar',
    origin: 'Faces medial e lateral do calcâneo (superfície plantar)',
    insertion: 'Margem posterolateral do tendão do flexor longo dos dedos',
    innervation: 'N. Plantar Lateral (S2-S3)',
    vascularization: 'Artérias plantares lateral e medial',
    veins: 'Veias plantares lateral e medial',
    action: 'Corrige a tração oblíqua do flexor longo; auxilia flexão dos dedos',
  },
  {
    id: 'lumbrical-1',
    region: 'Pé',
    compartment: 'Planta',
    subCompartment: '2ª Camada',
    name: '1º Lumbrical',
    origin: 'Tendão do FDL (medial) do 2º dedo',
    insertion: 'Expansão extensora e base da falange proximal do 2º dedo',
    innervation: 'N. Plantar Medial (S2-S3)',
    vascularization: 'Artérias plantares lateral e medial, arco plantar e artérias metatarsais plantares',
    veins: 'Arco venoso plantar e veias metatarsais',
    action: 'Flexão das articulações metatarsofalângicas; extensão das interfalângicas',
  },
  {
    id: 'lumbricais-2-4',
    region: 'Pé',
    compartment: 'Planta',
    subCompartment: '2ª Camada',
    name: '2º, 3º e 4º Lumbricais',
    origin: 'Tendões adjacentes do FDL',
    insertion: 'Expansões extensoras e bases das falanges proximais dos dedos 3-5',
    innervation: 'N. Plantar Lateral (S2-S3)',
    vascularization: 'Artérias plantares lateral e medial, arco plantar e artérias metatarsais plantares',
    veins: 'Arco venoso plantar e veias metatarsais',
    action: 'Flexão das articulações metatarsofalângicas; extensão das interfalângicas',
  },

  // PÉ - 3ª CAMADA
  {
    id: 'flex-curto-halux',
    region: 'Pé',
    compartment: 'Planta',
    subCompartment: '3ª Camada',
    name: 'Flexor Curto do Hálux',
    origin: 'Cuboide e cuneiforme lateral',
    insertion: 'Ambos os lados da base da falange proximal do hálux',
    innervation: 'N. Plantar Medial (S2-S3)',
    vascularization: 'Artéria plantar medial e primeira artéria metatarsal plantar',
    veins: 'Veia plantar medial',
    action: 'Flexão da falange proximal do hálux',
  },
  {
    id: 'adutor-halux',
    region: 'Pé',
    compartment: 'Planta',
    subCompartment: '3ª Camada',
    name: 'Adutor do Hálux',
    origin: '• Cabeça Oblíqua: bases dos metatarsos 2-4\n• Cabeça Transversa: ligamentos plantares das articulações MTF',
    insertion: 'Base da falange proximal do hálux (lateral)',
    innervation: 'N. Plantar Lateral (S2-S3)',
    vascularization: 'Artérias plantares medial e lateral e arco plantar',
    veins: 'Veias plantares e arco venoso plantar',
    action: 'Adução do hálux; auxilia arco transverso',
  },
  {
    id: 'flex-curto-minimo',
    region: 'Pé',
    compartment: 'Planta',
    subCompartment: '3ª Camada',
    name: 'Flexor Curto do Dedo Mínimo',
    origin: 'Base do 5º metatarso',
    insertion: 'Base da falange proximal do 5º dedo',
    innervation: 'N. Plantar Lateral (S2-S3)',
    vascularization: 'Artéria plantar lateral',
    veins: 'Veia plantar lateral',
    action: 'Flexão da falange proximal do 5º dedo',
  },
  
  // PÉ - 4ª CAMADA
  {
    id: 'inter-plantares',
    region: 'Pé',
    compartment: 'Planta',
    subCompartment: '4ª Camada',
    name: 'Interósseos Plantares (3 músculos)',
    origin: 'Bases e lados mediais dos metatarsos 3-5',
    insertion: 'Lados mediais das bases das falanges proximais dos dedos 3-5',
    innervation: 'N. Plantar Lateral (S2-S3)',
    vascularization: 'Arco plantar e artérias metatarsais plantares',
    veins: 'Veias metatarsais plantares',
    action: 'Adução dos dedos 3-5 (PAD) e flexão das MTF',
  },
  {
    id: 'inter-dorsais',
    region: 'Pé',
    compartment: 'Planta',
    subCompartment: '4ª Camada',
    name: 'Interósseos Dorsais (4 músculos)',
    origin: 'Lados adjacentes dos metatarsos 1-5',
    insertion: '1º: lado medial do 2º dedo; 2º-4º: lados laterais dos dedos 2-4',
    innervation: 'N. Plantar Lateral (S2-S3)',
    vascularization: 'Arco plantar e artérias metatarsais dorsais',
    veins: 'Veias metatarsais dorsais',
    action: 'Abdução dos dedos 2-4 (DAB) e flexão das MTF',
  },

  // PÉ - DORSO
  {
    id: 'ext-curto-dedos',
    region: 'Pé',
    compartment: 'Dorso',
    name: 'Extensor Curto dos Dedos',
    origin: 'Calcâneo (superfície superolateral)',
    insertion: 'Tendões do extensor longo nos dedos 2-4',
    innervation: 'N. Fibular Profundo (L4-S1)',
    vascularization: 'Artéria dorsal do pé e artéria társica lateral',
    veins: 'Veia dorsal do pé',
    action: 'Extensão dos dedos 2-4',
  },
  {
    id: 'ext-curto-halux',
    region: 'Pé',
    compartment: 'Dorso',
    name: 'Extensor Curto do Hálux',
    origin: 'Calcâneo (superfície superolateral)',
    insertion: 'Base da falange proximal do hálux',
    innervation: 'N. Fibular Profundo (L4-S1)',
    vascularization: 'Artéria dorsal do pé',
    veins: 'Veia dorsal do pé',
    action: 'Extensão do hálux',
  },
];