export interface QuizItem {
  id: string;
  category: string;
  question: string;
  answer: string;
}

export const QUIZ_DATA: QuizItem[] = [
  // Vascularização
  {
    id: 'vasc-1',
    category: 'Vascularização',
    question: 'RAMOS TERMINAIS DA ARTERIA AORTA ABDOMINAL.',
    answer: 'ARTERIA ILIACA COMUM DIREITA; ARTERIA ILIACA COMUM ESQUERDA',
  },
  {
    id: 'vasc-2',
    category: 'Vascularização',
    question: 'RAMOS TERMINAIS DA ARTERIA ILIACA COMUM',
    answer: 'ARTERIA ILIACA COMUM DIREITA → ILIACA EXTERNA DIREITA , ILIACA INTERNA DIREITA\nARTERIA ILIACA COMUM ESQUERDA→ ILIACA EXTERNA ESQUERDA, ILIACA EXTERNA ESQUERDA',
  },
  {
    id: 'vasc-3',
    category: 'Vascularização',
    question: 'RAMO TERMINAL DA ARTÉRIA ILIACA EXTERNA',
    answer: 'ARTERIA FEMORAL. O LIMITE DA ILIACA EXTERNA E A FERMORAL É O LIGAMENTO INGUINAL.',
  },
  {
    id: 'vasc-4',
    category: 'Vascularização',
    question: 'RAMOS COLATERAIS DA FEMORAL',
    answer: 'CIRCUNFLEXA ILIACA SUPERFICIAL + EPIGASTRICA SUPERFICIAL + FEMORAL PROFUNDA + PUDENDA EXTERNA SUPERFICIAL + PUDENDA EXTERNA PROFUNDA + DESCENDENTE DO JOELHO',
  },
  {
    id: 'vasc-5',
    category: 'Vascularização',
    question: 'PRINCIPAL ARTERIA QUE NUTRE A COXA',
    answer: 'FEMORAL PROFUNDA',
  },
  {
    id: 'vasc-6',
    category: 'Vascularização',
    question: 'RAMOS COLATERAIS DA FEMORAL PROFUNDA',
    answer: 'ARTERIAS PERFURANTES; CIRCUNFLEXA FEMORAL LATERAL. CIRCUNFLEXA FEMORAL MEDIAL',
  },
  {
    id: 'vasc-7',
    category: 'Vascularização',
    question: 'RAMO TERMINAL DA ARTERIA FEMORAL E SEU LIMITE',
    answer: 'ARTERIA POPLITEA. HIATO DOS ADUTORES.',
  },
  {
    id: 'vasc-8',
    category: 'Vascularização',
    question: 'RAMOS TERMINAIS DA ARTERIA POPLITEA',
    answer: 'TIBIAL ANTERIOR (PERFURA A MEMBRANA INTEROSSEA E FICA ANTERIOR NA PERNA) + TRONCO TIBIOFIBULAR (DÁ ORIGEM A ARTERIA TIBIAL POSTEIROR + ARTERIA FIBULAR)',
  },
  {
    id: 'vasc-9',
    category: 'Vascularização',
    question: 'RAMO TERMINAL DA TIBIAL ANTERIOR E LIMITE',
    answer: 'NO PÉ APÓS ATRAVESSAR O RETINACULO EXTENSOR INFERIOR, SE TORNANDO ARTERIA DORSAL DO PÉ',
  },
  {
    id: 'vasc-10',
    category: 'Vascularização',
    question: 'RAMOS TERMINAIS DA TIBIAL POSTERIOR NA PLANTA DO PE',
    answer: 'PLANTAR MEDIAL + PLANTAR LATERAL',
  },
  {
    id: 'vasc-11',
    category: 'Vascularização',
    question: 'ORIGEM DA VEIA SAFENA MAGNA E VEIA SAFENA PARVA',
    answer: 'ORIGINAL DO ARCO VENOSO DORSAL DO PÉ. SAFENA MAGNA MAIS MEDIAL. SAFENA PARVA MAIS LATERAL',
  },
  {
    id: 'vasc-12',
    category: 'Vascularização',
    question: 'A VEIA SAFENA PARVA É TRIBUTARIA DE QUEM?',
    answer: 'VEIA POPLITEA',
  },
  {
    id: 'vasc-13',
    category: 'Vascularização',
    question: 'RA DA SAFENA PARVA NA PERNA.',
    answer: 'N. SURAL',
  },
  {
    id: 'vasc-14',
    category: 'Vascularização',
    question: 'A VEIA SAFENA MAGNA É TRIBUTARIA DE QUEM?',
    answer: 'VEIA FEMORAL',
  },
  // Músculos
  {
    id: 'musc-1',
    category: 'Músculos',
    question: 'Quem faz a estabilização lateral do joelho?',
    answer: 'Trato iliotibial + bíceps femoral',
  },
  {
    id: 'musc-2',
    category: 'Músculos',
    question: 'Quem faz a estabilização medial do joelho?',
    answer: 'Pata de ganso (semitendíneo + sartório + grácil)',
  },
  {
    id: 'musc-3',
    category: 'Músculos',
    question: 'Quem faz estabilização anterior do joelho?',
    answer: 'Patela + ligamento patelar',
  },
  {
    id: 'musc-4',
    category: 'Músculos',
    question: 'Quem forma o quadríceps? Inervação?',
    answer: 'Vasto medial, vasto lateral, vasto intermédio, reto femoral – Todos inervados pelo N. FEMORAL (L2-L4)',
  },
  {
    id: 'musc-5',
    category: 'Músculos',
    question: 'Músculos extensores da coxa? E a inervação.',
    answer: 'Glúteo máximo (N. GLÚTEO INFERIOR L5-S2) + parte extensora do adutor magno (N. TIBIAL L4-S3) + semitendíneo (N. TIBIAL L5-S2) + semimembranaceo (N. TIBIAL L5-S2) + bíceps femoral (N. TIBIAL L5-S2 + N. FIBULAR COMUM L5-S2)',
  },
  {
    id: 'musc-6',
    category: 'Músculos',
    question: 'Músculos flexores da coxa? E a inervação de cada um.',
    answer: 'Reto femoral (N. FEMORAL L2-L4) + iliopsoas (RAMOS VENTRAIS L1-L3 + N. FEMORAL L2-L3) + sartório (N. FEMORAL L2-L3) + pectíneo (N. FEMORAL L2-L3) + adutor curto (N. OBTURADOR L2-L4) + tensor da fascia lata (N. GLÚTEO SUPERIOR L4-S1)',
  },
  {
    id: 'musc-7',
    category: 'Músculos',
    question: 'Músculos rotadores laterais da coxa? E a inervação de cada um.',
    answer: 'Iliopsoas + sartório (N. FEMORAL) + glúteo máximo (N. GLÚTEO INFERIOR) + piriforme (RAMOS VENTRAIS L5-S2) + gêmeo sup e obturador interno (N. DO OBTURADOR INTERNO) + gêmeo inferior e quadrado femoral (N. DO QUADRADO FEMORAL) + obturador externo (N. OBTURADOR)',
  },
  {
    id: 'musc-8',
    category: 'Músculos',
    question: 'Músculos rotadores mediais da coxa? E a inervação de cada um.',
    answer: 'Tensor da fáscia lata + glúteo médio + glúteo mínimo – todos pelo N. GLÚTEO SUPERIOR (L4-S1)',
  },
  {
    id: 'musc-9',
    category: 'Músculos',
    question: 'Músculos adutores da coxa? E a inervação de cada um.',
    answer: 'Pectíneo (N. FEMORAL L2-L3)+ adutor longo (N. OBTURADOR) + grácil (N. OBTURADOR) + adutor curto (N. OBTURADOR) + adutor magno (porção adutora- N. OBTURADOR)',
  },
  {
    id: 'musc-10',
    category: 'Músculos',
    question: 'Músculos abdutores da coxa? E a inervação de cada um.',
    answer: 'Tensor da fáscia lata + glúteo médio + glúteo mínimo + piriforme',
  },
  {
    id: 'musc-11',
    category: 'Músculos',
    question: 'Formação do tríceps sural',
    answer: 'Soleo + gastrocnêmio medial e lateral (inervados pelo N. TIBIAL S1-S2)',
  },
  {
    id: 'musc-12',
    category: 'Músculos',
    question: 'Músculos inervados pelo N. Femoral',
    answer: 'Quadríceps (Reto Femoral, Vastos) + Sartório + Iliopsoas (parte Ilíaco) + Pectíneo',
  },
  {
    id: 'musc-13',
    category: 'Músculos',
    question: 'Músculos inervados pelo N. Obturador (L2-L4)',
    answer: 'Adutor Longo + Grácil + Adutor Curto + Adutor Magno (porção adutora) + Obturador Externo',
  },
  {
    id: 'musc-14',
    category: 'Músculos',
    question: 'Músculos inervados pelo N. Tibial na coxa',
    answer: 'Adutor magno (cabeça extensora) + semimembranaceo + semitendíneo + bíceps femoral cabeça longa',
  },
  {
    id: 'musc-15',
    category: 'Músculos',
    question: 'Músculos inervados pelo N. Tibial na perna',
    answer: 'Parte posterior da perna – tibial posterior + flexor longo dos dedos + flexor longo do halux + poplíteo + plantar + tríceps Sural (soleo + gastrocnêmio medial e lateral)',
  },
  {
    id: 'musc-16',
    category: 'Músculos',
    question: 'Músculos inervados pelo N. Fibular Comum',
    answer: 'Cabeça curta do bíceps femoral',
  },
  {
    id: 'musc-17',
    category: 'Músculos',
    question: 'Músculos inervados pelo N. Fibular Superficial (L5-S1)',
    answer: 'Compartimento lateral da perna – fibular curto + fibular longo',
  },
  {
    id: 'musc-18',
    category: 'Músculos',
    question: 'Músculos inervados pelo N. Fibular Profundo (L4-S1)',
    answer: 'Tibial anterior + fibular terceiro + extensor longo dos dedos + extensor longo do halux + extensor curto dos dedos',
  },
  {
    id: 'musc-19',
    category: 'Músculos',
    question: 'Musculos com inserção na tuberosidade da tíbia e patela',
    answer: 'Quadríceps',
  },
  {
    id: 'musc-20',
    category: 'Músculos',
    question: 'Musculos com inserção no trato iliotibial',
    answer: 'Glúteo máximo + tensor da fáscia lata',
  },
  {
    id: 'musc-21',
    category: 'Músculos',
    question: 'Músculos com inserção no tendão do obturador interno',
    answer: 'Gêmeo superior + gêmeo inferior',
  },
  {
    id: 'musc-22',
    category: 'Músculos',
    question: 'Músculos com inserção no trocanter maior',
    answer: 'Glúteo médio + glúteo mínimo + piriforme + obturador interno',
  },
  {
    id: 'musc-23',
    category: 'Músculos',
    question: 'Músculos com origem no corpo do púbis',
    answer: 'Grácil + adutor longo + adutor curto',
  },
  {
    id: 'musc-24',
    category: 'Músculos',
    question: 'Músculos com origem no túber isquiático',
    answer: 'Semimembranaceo + semitendíneo + cabeça longa do bíceps femoral + porção extensora do adutor magno + quadrado femoral + gêmeo inferior',
  },
  {
    id: 'musc-25',
    category: 'Músculos',
    question: 'Conteúdo do compartimento anterior da perna',
    answer: 'Tibial anterior + extensor longo dos dedos + extensor longo do halux + fibular terceiro + artéria e veias tibiais anteriores + N. FIBULAR PROFUNDO (L4-S1)',
  },
  {
    id: 'musc-26',
    category: 'Músculos',
    question: 'Conteúdo do compartimento lateral da perna',
    answer: 'Fibular curto + fibular longo + N. FIBULAR SUPERFICIAL (L5-S1)',
  },
  {
    id: 'musc-27',
    category: 'Músculos',
    question: 'Conteúdo do compartimento posterior superficial da perna',
    answer: 'Tríceps sural + plantar (tendão)',
  },
  {
    id: 'musc-28',
    category: 'Músculos',
    question: 'Conteúdo do compartimento posterior profundo da perna',
    answer: 'Tibial posterior + poplíteo + flexor longo dos dedos + flexor longo do halux + artéria e veias tibiais posteriores + N. TIBIAL + artéria e veias fibulares',
  },
  {
    id: 'musc-29',
    category: 'Músculos',
    question: 'Músculos que fazem flexão da perna',
    answer: 'Sartório + grácil + bíceps femoral + semitendíneo + semimembranaceo + plantar + gastrocnêmio (medial + lateral)',
  },
  {
    id: 'musc-30',
    category: 'Músculos',
    question: 'Músculos que fazem extensão da perna',
    answer: 'Quadríceps (4 cabeças) – Vasto lateral + vasto medial + vasto intermédio + reto femoral',
  },
  {
    id: 'musc-31',
    category: 'Músculos',
    question: 'Músculos que fazem dorsiflexão',
    answer: 'Tibial anterior + extensor longo do halux + extensor longo dos dedos + fibular terceiro',
  },
  {
    id: 'musc-32',
    category: 'Músculos',
    question: 'Músculos que fazem flexão plantar',
    answer: 'Gastrocnemio + soleo + plantar + tibial posterior + Fibular curto + fibular longo + flexor longo dos dedos + flexor longo do halux',
  },
  {
    id: 'musc-33',
    category: 'Músculos',
    question: 'Principal musculo da flexão plantar',
    answer: 'Tríceps sural',
  },
  {
    id: 'musc-34',
    category: 'Músculos',
    question: 'Principal musculo da dorsiflexão',
    answer: 'Tibial anterior',
  },
  {
    id: 'musc-35',
    category: 'Músculos',
    question: 'Principal musculo na extensão da coxa',
    answer: 'Gluteo máximo',
  },
  {
    id: 'musc-36',
    category: 'Músculos',
    question: 'Principal musculo na flexão da coxa',
    answer: 'Iliopsoas',
  },
  {
    id: 'musc-37',
    category: 'Músculos',
    question: 'Músculos que fazem eversão do pé',
    answer: 'Fibular longo + fibular curto + fibular terceiro',
  },
  {
    id: 'musc-38',
    category: 'Músculos',
    question: 'Músculos que fazem inversão do pé',
    answer: 'Tibial anterior + tibial posterior',
  },
  {
    id: 'musc-39',
    category: 'Músculos',
    question: 'Formação do tendão de aquiles.',
    answer: 'Formado pelo tendão de inserção dos músculos que formam o tríceps sural',
  },
  {
    id: 'musc-40',
    category: 'Músculos',
    question: 'Inserção do tríceps sural',
    answer: 'Se insere no osso calcâneo',
  },
  {
    id: 'musc-41',
    category: 'Músculos',
    question: 'Quais são os músculos da jarrete',
    answer: 'Músculos da parte posterior da coxa',
  },

  // Plexo Lombrosacral
  {
    id: 'plexo-1',
    category: 'Plexo Lombrosacral e Nervos',
    question: 'Quais são as raízes do plexo lombar?',
    answer: 'L1, L2, L3, L4',
  },
  {
    id: 'plexo-2',
    category: 'Plexo Lombrosacral e Nervos',
    question: 'Quais são as raízes do plexo sacral?',
    answer: 'L4, L5, S1, S2, S3, S4',
  },
  {
    id: 'plexo-3',
    category: 'Plexo Lombrosacral e Nervos',
    question: 'Qual raiz é comum aos dois plexos?',
    answer: 'RAIZ DE L4',
  },
  {
    id: 'plexo-4',
    category: 'Plexo Lombrosacral e Nervos',
    question: 'Ramos do plexo lombar e suas raízes',
    answer: 'L1 – ILIOHIPOGASTRICO + ILIOINGUINAL\nL1 + L2 – GENITOFEMORAL\nL2 + L3 + L4 – FEMORAL\nL2 + L3 + L4 – OBTURADOR\nL4 + L5 – TRONCO LOMBOSACRAL',
  },
  {
    id: 'plexo-5',
    category: 'Plexo Lombrosacral e Nervos',
    question: 'Ramos do plexo sacral e suas raízes',
    answer: 'L4 + L5 + S1 – GLUTEO SUPERIOR\nL5 + S1 + S2 – GLUTEO INFERIOR\nS1 + S2 + S3 - CUTANEO FEMORAL POSTERIOR\nS2 + S3 + S4 - PUDENDO\nL4 + L5 + S1 + S2 + S3 – ISQUIATICO',
  },
  {
    id: 'plexo-6',
    category: 'Plexo Lombrosacral e Nervos',
    question: 'Inervação sensitiva da coxa',
    answer: 'N. FEMORAL + N. GENITOFEMORAL + N. OBTURADOR + N. CUTANEO FEMORAL LATERAL + N. CUTANEO FEMORAL POSTERIOR',
  },
  {
    id: 'plexo-7',
    category: 'Plexo Lombrosacral e Nervos',
    question: 'Inervação sensitiva da parte lateral da coxa',
    answer: 'N. CUTANEO FEMORAL LATERAL',
  },
  {
    id: 'plexo-8',
    category: 'Plexo Lombrosacral e Nervos',
    question: 'Inervação sensitiva da parte medial da coxa',
    answer: 'N. OBTURADOR + N. FEMORAL',
  },
  {
    id: 'plexo-9',
    category: 'Plexo Lombrosacral e Nervos',
    question: 'Inervação sensitiva da parte anterior da coxa',
    answer: 'N. GENITOFEMORAL + N. FEMORAL + N. CUTANEO FEMORAL LATERAL',
  },
  {
    id: 'plexo-10',
    category: 'Plexo Lombrosacral e Nervos',
    question: 'Inervação sensitiva da parte posterior da coxa',
    answer: 'N. CUTANEO FEMORAL POSTEIROR',
  },
  {
    id: 'plexo-11',
    category: 'Plexo Lombrosacral e Nervos',
    question: 'Inervação sensitiva da perna',
    answer: 'N. CUTANEO SURAL LATERAL + N. SAFENO + N. FIBULAR SUPERFICIAL + N. SURAL',
  },
  {
    id: 'plexo-12',
    category: 'Plexo Lombrosacral e Nervos',
    question: 'Inervação sensitiva da parte anterior da perna',
    answer: 'ANTERO LATERAL: N. CUTANEO SURAL LATERAL + N. FIBULAR SUPERFICIAL\nANTERO MEDIAL: N. SAFENO',
  },
  {
    id: 'plexo-13',
    category: 'Plexo Lombrosacral e Nervos',
    question: 'Inervação sensitiva da parte posterior da perna',
    answer: 'POSTERO MEDIAL: N. SAFENO\nPOSTERO LATERAL: N. SURAL + N. CUTANEO SURAL LATERAL + N. FIBULAR SUPERFICIAL',
  },
  {
    id: 'plexo-14',
    category: 'Plexo Lombrosacral e Nervos',
    question: 'Inervação sensitiva da parte lateral da perna',
    answer: 'LATERAL: N. SURAL + N. CUTANEO SURAL LATERAL + N. FIBULAR SUPERFICIAL',
  },
  {
    id: 'plexo-15',
    category: 'Plexo Lombrosacral e Nervos',
    question: 'Inervação sensitiva da parte medial da perna',
    answer: 'MEDIAL: N. SAFENO',
  },
  {
    id: 'plexo-16',
    category: 'Plexo Lombrosacral e Nervos',
    question: 'Inervação sensitiva do dorso do pe',
    answer: 'N. FIBULAR PROFUNDO (ENTRE O HALUX E DEDO 2) + N. FIBULAR SUPERFICIAL + N. SURAL + N. SAFENO (UM POUCO)',
  },
  {
    id: 'plexo-17',
    category: 'Plexo Lombrosacral e Nervos',
    question: 'Inervação sensitiva da planta do pé',
    answer: 'N. SURAL + N. TIBIAL + N. SAFENO',
  },
  {
    id: 'plexo-18',
    category: 'Plexo Lombrosacral e Nervos',
    question: 'Inervação sensitiva do pé',
    answer: 'N. FIBULAR SUPERFICIAL + N. FIBULAR PROFUNDO + N. SURAL + N. TIBIAL + N. SAFENO',
  },
  {
    id: 'plexo-19',
    category: 'Plexo Lombrosacral e Nervos',
    question: 'O N. Isquiático inerva sensitivamente a coxa? Quais são os seus ramos terminais?',
    answer: 'Não. Ramos terminais: N. FIBULAR COMUM + N. TIBIAL.',
  },
  {
    id: 'plexo-20',
    category: 'Plexo Lombrosacral e Nervos',
    question: 'Ramos colaterais e terminais do N. Fibular Comum. Função dos dois na perna.',
    answer: 'Colateral: cutâneo sural lateral\nTerminal: fibular superficial + fibular profundo\nCutâneo sural lateral -> inervação sensitiva da perna\nFibular superficial -> inervação sensitiva da perna + inervação motora do fibular curto + fibular longo\nFibular profundo -> inervação motora do fibular terceiro + tibial anterior + extensor longo do halux + extensor longo dos dedos',
  },
  {
    id: 'plexo-21',
    category: 'Plexo Lombrosacral e Nervos',
    question: 'Como é formado o N. Safeno? é motor?',
    answer: 'Ramo terminal do N. FEMORAL. Nervo sensitivo na perna.',
  },
  {
    id: 'plexo-22',
    category: 'Plexo Lombrosacral e Nervos',
    question: 'Função do N. Tibial na perna. É sensitivo na perna?',
    answer: 'N. TIBIAL é motor na perna, inerva todos os músculos posteriores. Músculos: Tibial posterior + flexor longo do halux + flexor longo dos dedos + poplíteo + plantar + tríceps Sural (gastrocnêmio medial e lateral + sóleo)',
  },
  {
    id: 'plexo-23',
    category: 'Plexo Lombrosacral e Nervos',
    question: 'Como é formado o N. Sural?',
    answer: 'Formado por ramos do N. TIBIAL e N. FIBULAR COMUM. O N. TIBIAL dá o nervo cutâneo sural medial. Já o N. FIBULAR COMUM dá o nervo cutâneo sural lateral, que dá o ramo fibular comunicante. Os nervos: cutâneo sural medial + fibular comunicante se juntam e formam o N. SURAL.',
  },
  {
    id: 'plexo-24',
    category: 'Plexo Lombrosacral e Nervos',
    question: 'Inervação da parte anterior da perna',
    answer: 'N. FIBULAR PROFUNDO',
  },
  {
    id: 'plexo-25',
    category: 'Plexo Lombrosacral e Nervos',
    question: 'Inervação da parte lateral da perna',
    answer: 'N. FIBULAR SUPERFICIAL',
  },
  {
    id: 'plexo-26',
    category: 'Plexo Lombrosacral e Nervos',
    question: 'Inervação da parte posterior profunda',
    answer: 'N. TIBIAL',
  },
  {
    id: 'plexo-27',
    category: 'Plexo Lombrosacral e Nervos',
    question: 'Inervação da parte posterior superficial da perna',
    answer: 'N. TIBIAL',
  },
  {
    id: 'plexo-28',
    category: 'Plexo Lombrosacral e Nervos',
    question: 'Inervação sensitiva do trígono femoral',
    answer: 'N. GENITO FEMORAL',
  },
  {
    id: 'plexo-29',
    category: 'Plexo Lombrosacral e Nervos',
    question: 'Inervação sensitiva da fossa poplítea',
    answer: 'N. CUTANEO SURAL LATERAL',
  },
  {
    id: 'plexo-30',
    category: 'Plexo Lombrosacral e Nervos',
    question: 'Nervo sensitivo da parte medial da perna e sua origem',
    answer: 'N. SAFENO, origem do N. FEMORAL',
  },
  {
    id: 'plexo-31',
    category: 'Plexo Lombrosacral e Nervos',
    question: 'Local de aplicação de injeções no glúteo e motivo',
    answer: 'Quadrante superior lateral, para não atingir vasos e o N. ISQUIÁTICO',
  },
  {
    id: 'plexo-32',
    category: 'Plexo Lombrosacral e Nervos',
    question: 'Inervação maléolo medial',
    answer: 'N. SAFENO',
  },
  {
    id: 'plexo-33',
    category: 'Plexo Lombrosacral e Nervos',
    question: 'Inervação maléolo lateral',
    answer: 'N. SURAL',
  },
  {
    id: 'plexo-34',
    category: 'Plexo Lombrosacral e Nervos',
    question: 'Inervação entre os maléolos',
    answer: 'N. SAFENO + N. FIBULAR SUPERFICIAL',
  },
  {
    id: 'plexo-35',
    category: 'Plexo Lombrosacral e Nervos',
    question: 'Inervação sensitiva exercida pelo N. Fibular Superficial na perna e pe',
    answer: 'Inervação da parte ínfero anterior lateral da perna. No pe, inerva a maior parte do dorso do pé',
  },

  // Prova Final A
  {
    id: 'prova-a-1',
    category: 'Prova Final A',
    question: 'Qual a origem do sartório?',
    answer: 'Ele se origina da espinha iliaca anterosuperior',
  },
  {
    id: 'prova-a-2',
    category: 'Prova Final A',
    question: 'Qual a formação do N. Obturatório?',
    answer: 'Formado pelas divisões anteriores das raízes L2, L3 e L4 do plexo lombar',
  },
  {
    id: 'prova-a-3',
    category: 'Prova Final A',
    question: 'Quais dedos do pé tem interósseos dorsais e suas origens',
    answer: 'O quarto e terceiro dedo possuem um interósseo dorsal em cada e o segundo dedo possui dois interósseos dorsais. Eles se originam das bases dos metatarsos adjacentes, logo cada interósseo se origina de dois metatarsos',
  },
  {
    id: 'prova-a-4',
    category: 'Prova Final A',
    question: 'Quais os limites do trígono femoral?',
    answer: 'Limite superior: ligamento inguinal\nLimite medial: margem lateral do adutor longo\nLimite lateral: margem medial do sartório\nAssoalho: Iliopsoas e Pectíneo\nTeto: fáscia lata',
  },
  {
    id: 'prova-a-5',
    category: 'Prova Final A',
    question: 'Com qual tendão a segunda camada do pé tem relação?',
    answer: 'Com o tendão do flexor longo dos dedos',
  },
  {
    id: 'prova-a-6',
    category: 'Prova Final A',
    question: 'Cite 2 principais flexores da coxa?',
    answer: 'Iliopsoas e Reto femoral',
  },
  {
    id: 'prova-a-7',
    category: 'Prova Final A',
    question: 'Qual a inervação dos lumbricais?',
    answer: 'O primeiro é inervado pelo N. PLANTAR MEDIAL (S2-S3) e os demais três são inervados pelo N. PLANTAR LATERAL (S2-S3)',
  },
  {
    id: 'prova-a-8',
    category: 'Prova Final A',
    question: 'Cite os limites e o conteúdo do canal dos adutores?',
    answer: 'Limite anterior(teto): sartório\nLimite lateral: vasto medial\nLimite posteromedial: Adutor Longo e talvez o Magno\nConteúdo: N. SAFENO, nervo para o vasto medial,veia femoral e artéria femoral',
  },
  {
    id: 'prova-a-9',
    category: 'Prova Final A',
    question: 'Quais os nervos exclusivamente sensitivos que saem do forame isquiático maior?',
    answer: 'N. CUTÂNEO POSTERIOR FEMORAL e N. PUDENDO',
  },
  {
    id: 'prova-a-10',
    category: 'Prova Final A',
    question: 'Qual a origem dos músculos posteriores da coxa?',
    answer: 'O semitendíneo, semimembranáceo e cabeça longa do bíceps femoral se originam do túber isquiático, enquanto a cabeça curta do bíceps se origina da linha áspera do fêmur',
  },
  {
    id: 'prova-a-11',
    category: 'Prova Final A',
    question: 'Qual a inervação do N. Safeno no pé e na perna?',
    answer: 'O N. SAFENO inerva sensitivamente a metade medial abaixo da fossa poplítea no posterior da perna, e a metade medial da parte anterior da perna. Já no pé, ele inerva uma pequena porção medial na planta e dorso do pé próxima ao calcanhar (não chega nos dedos).',
  },
  {
    id: 'prova-a-12',
    category: 'Prova Final A',
    question: 'Inervação sensitiva exercida pelo N. Plantar Lateral da planta do pé',
    answer: 'O N. PLANTAR LATERAL no pé inerva a parte lateral da planta a partir da metade lateral do quarto dedo, com exceção de uma pequena parte na lateral próxima ao calcanhar que é inervada pelo sural',
  },
  {
    id: 'prova-a-13',
    category: 'Prova Final A',
    question: 'Onde fica o hiato tendíneo e qual o seu conteúdo?',
    answer: 'O hiato tendíneo dos adutor é um orifício na inserção do adutor magno, e nele passam a artéria femoral tornando poplítea e a veia poplítea tornando femoral',
  },
  {
    id: 'prova-a-14',
    category: 'Prova Final A',
    question: 'Principal músculo que faz a extensão e rotação lateral da coxa?',
    answer: 'Glúteo máximo',
  },
  {
    id: 'prova-a-15',
    category: 'Prova Final A',
    question: 'Quem faz a estabilização lateral do joelho?',
    answer: 'Trato iliotibial, tendão de inserção do bíceps e ligamento colateral fibular',
  },
  {
    id: 'prova-a-16',
    category: 'Prova Final A',
    question: 'Quem faz a eversão do pé e sua inervação?',
    answer: 'Fibular curto e longo, inervados pelo N. FIBULAR SUPERFICIAL (L5-S1) e fibular terceiro inervado pelo N. FIBULAR PROFUNDO (L4-S1)',
  },
  {
    id: 'prova-a-17',
    category: 'Prova Final A',
    question: 'Compartimento fibular pertence a qual região?',
    answer: 'A região lateral da perna, posteriormente ao maléolo lateral',
  },
  {
    id: 'prova-a-18',
    category: 'Prova Final A',
    question: 'Quais os músculos da primeira camada da planta do pé e sua inervação?',
    answer: 'Abdutor do hálux e Flexor curto dos dedos, inervados pelo N. PLANTAR MEDIAL (S2-S3) e abdutor do dedo mínimo inervado pelo N. PLANTAR LATERAL (S2-S3)',
  },
  {
    id: 'prova-a-19',
    category: 'Prova Final A',
    question: 'Qual músculo que se insere nos sesamóides do hálux?',
    answer: 'Flexor curto do hálux',
  },
  {
    id: 'prova-a-20',
    category: 'Prova Final A',
    question: 'Quais músculos se inserem no tendão do obturador interno?',
    answer: 'Gêmeo superior e inferior',
  },

  // Prova Final B
  {
    id: 'prova-b-1',
    category: 'Prova Final B',
    question: 'Qual a origem poplíteo?',
    answer: 'Côndilo lateral do fêmur e menisco lateral',
  },
  {
    id: 'prova-b-2',
    category: 'Prova Final B',
    question: 'Qual a formação do N. Sural?',
    answer: 'Ele é formado pela junção do N. CUTÂNEO SURAL MEDIAL com o ramo fibular comunicante vindo do N. CUTÂNEO SURAL LATERAL',
  },
  {
    id: 'prova-b-3',
    category: 'Prova Final B',
    question: 'Qual a formação do N. Femoral',
    answer: 'Formado pelas divisões posteriores das raízes L2, L3 e L4 do plexo lombar',
  },
  {
    id: 'prova-b-4',
    category: 'Prova Final B',
    question: 'Qual a origem do ligamento poplíteo oblíquo?',
    answer: 'Ele é originado de um espessamento do tendão de uma das inserções do semimembranáceo, logo, no côndilo lateral do fêmur',
  },
  {
    id: 'prova-b-5',
    category: 'Prova Final B',
    question: 'Quais músculos que inserem no trato iliotibial?',
    answer: 'Glúteo máximo e tensor da fáscia lata',
  },
  {
    id: 'prova-b-6',
    category: 'Prova Final B',
    question: 'Quais os inversores do pé e sua inervação?',
    answer: 'Tibial anterior inervado pelo N. FIBULAR PROFUNDO (L4-S1) e Tibial posterior inervado pelo N. TIBIAL (L4-L5)',
  },
  {
    id: 'prova-b-7',
    category: 'Prova Final B',
    question: 'Quais dedos possuem interósseo plantar e sua inserção?',
    answer: 'O terceiro, quarto e quinto dedo, e eles se inserem na medial das bases das falanges proximais, logo, eles estão na parte medial dos dedos em questão',
  },
  {
    id: 'prova-b-8',
    category: 'Prova Final B',
    question: 'Quais músculos realizam a abdução da coxa e sua inervação?',
    answer: 'Glúteo mínimo e médio, ambos inervados pelo N. GLÚTEO SUPERIOR (L4-S1)',
  },
  {
    id: 'prova-b-9',
    category: 'Prova Final B',
    question: 'Cite três músculos adutores da coxa e suas origens',
    answer: 'Adutor Longo, ele se origina no corpo do púbis\nAdutor curto, ele se origina no corpo e ramo inferior do púbis\nGrácil, ele se origina no corpo e ramo inferior do púbis\nAdutor magno, sua porção adutora se origina do ramo inferior do púbis e ísquio',
  },
  {
    id: 'prova-b-10',
    category: 'Prova Final B',
    question: 'Onde a cápsula da articulação coxofemoral se insere?',
    answer: 'Na linha intertrocantérica',
  },
  {
    id: 'prova-b-11',
    category: 'Prova Final B',
    question: 'Inervação sensitiva exercida pelo N. Fibular Superficial na perna e pé?',
    answer: 'Ele inerva a porção anterolateral da perna e já no dorso do pé, ele inerva a maior parte da planta com exceção de uma pequena porção medial do N. SAFENO e da metade lateral do hálux e metade medial do segundo dedo',
  },
  {
    id: 'prova-b-12',
    category: 'Prova Final B',
    question: 'Inervação sensitiva do N. Fibular Profundo no dorso do pé?',
    answer: 'Metade lateral do hálux e metade medial do segundo dedo',
  },
  {
    id: 'prova-b-13',
    category: 'Prova Final B',
    question: 'Com qual osso do tarso a primeira e segunda camada estão relacionadas?',
    answer: 'Calcâneo',
  },
  {
    id: 'prova-b-14',
    category: 'Prova Final B',
    question: 'Qual o conteúdo principal do trígono femoral de lateral para medial?',
    answer: 'N. FEMORAL (L2-L4), artéria femoral e veia femoral',
  },
  {
    id: 'prova-b-15',
    category: 'Prova Final B',
    question: 'Quais músculos formam o tendão de Aquiles e onde ele se insere?',
    answer: 'O tríceps sural , logo, pelo gastrocnêmio lateral e medial e pelo sóleo. Ele se insere na tuberosidade do calcâneo',
  },
  {
    id: 'prova-b-16',
    category: 'Prova Final B',
    question: 'Qual o único músculo do posterior do membro que é inervado pelo N. Fibular Comum?',
    answer: 'A cabeça curta do bíceps femoral',
  },
  {
    id: 'prova-b-17',
    category: 'Prova Final B',
    question: 'Quem estabiliza o joelho na medial?',
    answer: 'Pata de ganso (semitendíneo, grácil e sartório) e ligamento colateral tibial',
  },
  {
    id: 'prova-b-18',
    category: 'Prova Final B',
    question: 'Inervação sensitiva do N. Plantar Lateral na planta do pé',
    answer: 'Ele inerva a lateral da planta do pé a partir da metade lateral do quarto dedo, com exceção de uma pequena porção lateral perto do calcanhar inervada pelo N. SURAL',
  },
  {
    id: 'prova-b-19',
    category: 'Prova Final B',
    question: 'Formação do arco profundo',
    answer: 'Artéria plantar lateral e ramo plantar profundo',
  },
  {
    id: 'prova-b-20',
    category: 'Prova Final B',
    question: 'Qual a artéria da coxa que cuida da vascularização muscular?',
    answer: 'Artéria femoral profunda',
  },

  // Pontos de Atenção Prof. Márcio
  {
    id: 'marcio-1',
    category: 'Pontos de Atenção (Prof. Márcio)',
    question: 'Quais músculos se inserem no Trato Iliotibial?',
    answer: 'Recebe inserção do glúteo máximo e do tensor da fáscia lata.',
  },
  {
    id: 'marcio-2',
    category: 'Pontos de Atenção (Prof. Márcio)',
    question: 'Quais músculos se inserem no Tendão do Obturador Interno?',
    answer: 'Os músculos gêmeos superior e inferior se inserem nele.',
  },
  {
    id: 'marcio-3',
    category: 'Pontos de Atenção (Prof. Márcio)',
    question: 'Qual a formação e inserção do Tendão de Aquiles (Calcâneo)?',
    answer: 'Formado pelo tríceps sural (gastrocnêmio medial, lateral e sóleo), insere-se na tuberosidade do calcâneo.',
  },
  {
    id: 'marcio-4',
    category: 'Pontos de Atenção (Prof. Márcio)',
    question: 'Quais são os principais músculos flexores da coxa?',
    answer: 'Iliopsoas e Reto femoral são os principais.',
  },
  {
    id: 'marcio-5',
    category: 'Pontos de Atenção (Prof. Márcio)',
    question: 'Qual o principal músculo para extensão e rotação lateral da coxa?',
    answer: 'Glúteo máximo.',
  },
  {
    id: 'marcio-6',
    category: 'Pontos de Atenção (Prof. Márcio)',
    question: 'Quais músculos realizam a abdução da coxa?',
    answer: 'Glúteo mínimo e médio.',
  },
  {
    id: 'marcio-7',
    category: 'Pontos de Atenção (Prof. Márcio)',
    question: 'Quais músculos realizam a eversão do pé?',
    answer: 'Fibular curto e longo; fibular terceiro.',
  },
  {
    id: 'marcio-8',
    category: 'Pontos de Atenção (Prof. Márcio)',
    question: 'Quais músculos realizam a inversão do pé?',
    answer: 'Tibial anterior e tibial posterior.',
  },
  {
    id: 'marcio-9',
    category: 'Pontos de Atenção (Prof. Márcio)',
    question: 'Quais estruturas realizam a estabilização lateral do joelho?',
    answer: 'Trato iliotibial, tendão de inserção do bíceps e ligamento colateral fibular.',
  },
  {
    id: 'marcio-10',
    category: 'Pontos de Atenção (Prof. Márcio)',
    question: 'Quais estruturas realizam a estabilização medial do joelho?',
    answer: 'Pata de ganso (semitendíneo, grácil e sartório) e ligamento colateral tibial.',
  },
  {
    id: 'marcio-11',
    category: 'Pontos de Atenção (Prof. Márcio)',
    question: 'Qual a origem do Ligamento Poplíteo Oblíquo?',
    answer: 'Originado de um espessamento do tendão do semimembranáceo.',
  },
  {
    id: 'marcio-12',
    category: 'Pontos de Atenção (Prof. Márcio)',
    question: 'Onde a cápsula da articulação coxofemoral se insere?',
    answer: 'Insere-se na linha intertrocantérica.',
  },
  {
    id: 'marcio-13',
    category: 'Pontos de Atenção (Prof. Márcio)',
    question: 'Descreva os limites e conteúdo do Trígono Femoral.',
    answer: 'Limites: Superior (ligamento inguinal) , medial (margem lateral do adutor longo) , lateral (margem medial do sartório) , assoalho (iliopsoas e pectíneo) , teto (fáscia lata).\nConteúdo (de lateral para medial): N. FEMORAL (L2-L4), artéria femoral e veia femoral.',
  },
  {
    id: 'marcio-14',
    category: 'Pontos de Atenção (Prof. Márcio)',
    question: 'Descreva os limites e conteúdo do Canal dos Adutores.',
    answer: 'Limites: Anterior/Teto (sartório) , lateral (vasto medial) , posteromedial (adutor longo e magno).\nConteúdo: N. SAFENO, nervo para o vasto medial, veia femoral e artéria femoral.',
  },
  {
    id: 'marcio-15',
    category: 'Pontos de Atenção (Prof. Márcio)',
    question: 'Onde se localiza o Hiato Tendíneo (dos Adutores) e qual seu conteúdo?',
    answer: 'Localização: Orifício na inserção do adutor magno.\nConteúdo: Artéria femoral (tornando-se poplítea) e veia poplítea (tornando-se femoral).',
  },
  {
    id: 'marcio-16',
    category: 'Pontos de Atenção (Prof. Márcio)',
    question: 'Onde se localiza o Compartimento Fibular?',
    answer: 'Região lateral da perna.',
  },
];